@echo off
echo generating test/%1.asm...
bin\cpasm.exe test/%1.txt -o test/%1.asm -asm NASM -arch x86_64 -env win64
echo compiling test/%1.obj...
nasm -f win64 test/%1.asm -o test/%1.obj
echo linking test/%1.exe...
gcc test/%1.obj -o test/%1.exe
