@echo off
:: run_win64_test.bat <test_name>
echo generating test/%1/%1-win64.asm...
bin\cropall.exe test/%1/%1.txt -o test/%1/%1-win64.asm -asm NASM -arch x86_64 -env win64
echo generating test/lib/lib-win64.asm...
bin\cropall.exe test/lib/lib.txt -o test/lib/lib-win64.asm -asm NASM -arch x86_64 -env win64

echo compiling test/%1/%1.obj...
nasm -f win64 test/%1/%1-win64.asm -o test/%1/%1.obj
echo compiling test/lib.obj...
nasm -f win64 test/lib/lib-win64.asm -o test/lib/lib.obj

echo linking test/%1/%1.exe...
gcc test/%1/%1.obj test/lib/lib.obj -o test/%1/%1.exe
