@echo off
:: run_linux_test.bat <test_name>
echo generating test/%1/%1-linux.asm...
bin\cropall.exe test/%1/%1.txt -o test/%1/%1-linux.asm -asm NASM -arch x86_64 -env linux
echo generating test/lib/lib-linux.asm...
bin\cropall.exe test/lib/lib.txt -o test/lib/lib-linux.asm -asm NASM -arch x86_64 -env linux

::echo compiling test/%1/%1.o...
::nasm -f elf test/%1/%1-linux.asm -o test/%1/%1.o
::echo compiling test/lib.o...
::nasm -f elf test/lib/lib-linux.asm -o test/lib/lib.o

::echo linking test/%1/%1.exe...
::gcc test/%1/%1.o test/lib/lib.o -o test/%1/%1.elf
